[package]
name = "cli-task-manager"
version = "0.1.0"
edition = "2021"
authors = ["Nkwenti-Severian"]

[dependencies]
clap = "4.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"